<?php

use Illuminate\Database\Seeder;

class InventoryTransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('inventory_transactions')->delete();
        
        \DB::table('inventory_transactions')->insert(
            [
            0 =>
            [
                'id' => 35,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:02:28',
                'transaction_modified_date' => '2006-03-22 16:02:28',
                'product_id' => 80,
                'quantity' => 75,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            1 =>
            [
                'id' => 36,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:02:48',
                'transaction_modified_date' => '2006-03-22 16:02:48',
                'product_id' => 72,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            2 =>
            [
                'id' => 37,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:04',
                'transaction_modified_date' => '2006-03-22 16:03:04',
                'product_id' => 52,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            3 =>
            [
                'id' => 38,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:09',
                'transaction_modified_date' => '2006-03-22 16:03:09',
                'product_id' => 56,
                'quantity' => 120,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            4 =>
            [
                'id' => 39,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:14',
                'transaction_modified_date' => '2006-03-22 16:03:14',
                'product_id' => 57,
                'quantity' => 80,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            5 =>
            [
                'id' => 40,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:40',
                'transaction_modified_date' => '2006-03-22 16:03:40',
                'product_id' => 6,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            6 =>
            [
                'id' => 41,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:47',
                'transaction_modified_date' => '2006-03-22 16:03:47',
                'product_id' => 7,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            7 =>
            [
                'id' => 42,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:03:54',
                'transaction_modified_date' => '2006-03-22 16:03:54',
                'product_id' => 8,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            8 =>
            [
                'id' => 43,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:02',
                'transaction_modified_date' => '2006-03-22 16:04:02',
                'product_id' => 14,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            9 =>
            [
                'id' => 44,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:07',
                'transaction_modified_date' => '2006-03-22 16:04:07',
                'product_id' => 17,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            10 =>
            [
                'id' => 45,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:12',
                'transaction_modified_date' => '2006-03-22 16:04:12',
                'product_id' => 19,
                'quantity' => 20,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            11 =>
            [
                'id' => 46,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:17',
                'transaction_modified_date' => '2006-03-22 16:04:17',
                'product_id' => 20,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            12 =>
            [
                'id' => 47,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:20',
                'transaction_modified_date' => '2006-03-22 16:04:20',
                'product_id' => 21,
                'quantity' => 20,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            13 =>
            [
                'id' => 48,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:24',
                'transaction_modified_date' => '2006-03-22 16:04:24',
                'product_id' => 40,
                'quantity' => 120,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            14 =>
            [
                'id' => 49,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:28',
                'transaction_modified_date' => '2006-03-22 16:04:28',
                'product_id' => 41,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            15 =>
            [
                'id' => 50,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:31',
                'transaction_modified_date' => '2006-03-22 16:04:31',
                'product_id' => 48,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            16 =>
            [
                'id' => 51,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:38',
                'transaction_modified_date' => '2006-03-22 16:04:38',
                'product_id' => 51,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            17 =>
            [
                'id' => 52,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:41',
                'transaction_modified_date' => '2006-03-22 16:04:41',
                'product_id' => 74,
                'quantity' => 20,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            18 =>
            [
                'id' => 53,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:04:45',
                'transaction_modified_date' => '2006-03-22 16:04:45',
                'product_id' => 77,
                'quantity' => 60,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            19 =>
            [
                'id' => 54,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:07',
                'transaction_modified_date' => '2006-03-22 16:05:07',
                'product_id' => 3,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            20 =>
            [
                'id' => 55,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:11',
                'transaction_modified_date' => '2006-03-22 16:05:11',
                'product_id' => 4,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            21 =>
            [
                'id' => 56,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:14',
                'transaction_modified_date' => '2006-03-22 16:05:14',
                'product_id' => 5,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            22 =>
            [
                'id' => 57,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:26',
                'transaction_modified_date' => '2006-03-22 16:05:26',
                'product_id' => 65,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            23 =>
            [
                'id' => 58,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:32',
                'transaction_modified_date' => '2006-03-22 16:05:32',
                'product_id' => 66,
                'quantity' => 80,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            24 =>
            [
                'id' => 59,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:47',
                'transaction_modified_date' => '2006-03-22 16:05:47',
                'product_id' => 1,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            25 =>
            [
                'id' => 60,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:05:51',
                'transaction_modified_date' => '2006-03-22 16:05:51',
                'product_id' => 34,
                'quantity' => 60,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            26 =>
            [
                'id' => 61,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:06:00',
                'transaction_modified_date' => '2006-03-22 16:06:00',
                'product_id' => 43,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            27 =>
            [
                'id' => 62,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-22 16:06:03',
                'transaction_modified_date' => '2006-03-22 16:06:03',
                'product_id' => 81,
                'quantity' => 125,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            28 =>
            [
                'id' => 63,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:07:56',
                'transaction_modified_date' => '2006-03-24 11:03:00',
                'product_id' => 80,
                'quantity' => 30,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            29 =>
            [
                'id' => 64,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:08:19',
                'transaction_modified_date' => '2006-03-22 16:08:59',
                'product_id' => 7,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            30 =>
            [
                'id' => 65,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:08:29',
                'transaction_modified_date' => '2006-03-22 16:08:59',
                'product_id' => 51,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            31 =>
            [
                'id' => 66,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:08:37',
                'transaction_modified_date' => '2006-03-22 16:08:59',
                'product_id' => 80,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            32 =>
            [
                'id' => 67,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:09:46',
                'transaction_modified_date' => '2006-03-22 16:10:27',
                'product_id' => 1,
                'quantity' => 15,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            33 =>
            [
                'id' => 68,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:10:06',
                'transaction_modified_date' => '2006-03-22 16:10:27',
                'product_id' => 43,
                'quantity' => 20,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            34 =>
            [
                'id' => 69,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:11:39',
                'transaction_modified_date' => '2006-03-24 11:00:55',
                'product_id' => 19,
                'quantity' => 20,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            35 =>
            [
                'id' => 70,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:11:56',
                'transaction_modified_date' => '2006-03-24 10:59:41',
                'product_id' => 48,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            36 =>
            [
                'id' => 71,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-22 16:12:29',
                'transaction_modified_date' => '2006-03-24 10:57:38',
                'product_id' => 8,
                'quantity' => 17,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            37 =>
            [
                'id' => 72,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:41:30',
                'transaction_modified_date' => '2006-03-24 10:41:30',
                'product_id' => 81,
                'quantity' => 200,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            38 =>
            [
                'id' => 73,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:41:33',
                'transaction_modified_date' => '2006-03-24 10:41:42',
                'product_id' => 81,
                'quantity' => 200,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #40',
            ],
            39 =>
            [
                'id' => 74,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:53:13',
                'transaction_modified_date' => '2006-03-24 10:53:13',
                'product_id' => 48,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            40 =>
            [
                'id' => 75,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:53:16',
                'transaction_modified_date' => '2006-03-24 10:55:46',
                'product_id' => 48,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #39',
            ],
            41 =>
            [
                'id' => 76,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:53:36',
                'transaction_modified_date' => '2006-03-24 10:53:36',
                'product_id' => 43,
                'quantity' => 300,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            42 =>
            [
                'id' => 77,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:53:39',
                'transaction_modified_date' => '2006-03-24 10:56:57',
                'product_id' => 43,
                'quantity' => 300,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #38',
            ],
            43 =>
            [
                'id' => 78,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:54:04',
                'transaction_modified_date' => '2006-03-24 10:54:04',
                'product_id' => 41,
                'quantity' => 200,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            44 =>
            [
                'id' => 79,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:54:07',
                'transaction_modified_date' => '2006-03-24 10:58:40',
                'product_id' => 41,
                'quantity' => 200,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #36',
            ],
            45 =>
            [
                'id' => 80,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:54:33',
                'transaction_modified_date' => '2006-03-24 10:54:33',
                'product_id' => 19,
                'quantity' => 30,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            46 =>
            [
                'id' => 81,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:54:35',
                'transaction_modified_date' => '2006-03-24 11:02:02',
                'product_id' => 19,
                'quantity' => 30,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #33',
            ],
            47 =>
            [
                'id' => 82,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-03-24 10:54:58',
                'transaction_modified_date' => '2006-03-24 10:54:58',
                'product_id' => 34,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            48 =>
            [
                'id' => 83,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 10:55:02',
                'transaction_modified_date' => '2006-03-24 11:03:00',
                'product_id' => 34,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #30',
            ],
            49 =>
            [
                'id' => 84,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:48:15',
                'transaction_modified_date' => '2006-04-04 11:41:14',
                'product_id' => 6,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            50 =>
            [
                'id' => 85,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:48:23',
                'transaction_modified_date' => '2006-04-04 11:41:14',
                'product_id' => 4,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            51 =>
            [
                'id' => 86,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-24 14:49:16',
                'transaction_modified_date' => '2006-03-24 14:49:16',
                'product_id' => 80,
                'quantity' => 20,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            52 =>
            [
                'id' => 87,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-24 14:49:20',
                'transaction_modified_date' => '2006-03-24 14:49:20',
                'product_id' => 81,
                'quantity' => 50,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            53 =>
            [
                'id' => 88,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-24 14:50:09',
                'transaction_modified_date' => '2006-03-24 14:50:09',
                'product_id' => 1,
                'quantity' => 25,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            54 =>
            [
                'id' => 89,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-24 14:50:14',
                'transaction_modified_date' => '2006-03-24 14:50:14',
                'product_id' => 43,
                'quantity' => 25,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            55 =>
            [
                'id' => 90,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-24 14:50:18',
                'transaction_modified_date' => '2006-03-24 14:50:18',
                'product_id' => 81,
                'quantity' => 25,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            56 =>
            [
                'id' => 91,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:51:03',
                'transaction_modified_date' => '2006-04-04 11:09:24',
                'product_id' => 40,
                'quantity' => 50,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            57 =>
            [
                'id' => 92,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:55:03',
                'transaction_modified_date' => '2006-04-04 11:06:56',
                'product_id' => 21,
                'quantity' => 20,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            58 =>
            [
                'id' => 93,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:55:39',
                'transaction_modified_date' => '2006-04-04 11:06:13',
                'product_id' => 5,
                'quantity' => 25,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            59 =>
            [
                'id' => 94,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:55:52',
                'transaction_modified_date' => '2006-04-04 11:06:13',
                'product_id' => 41,
                'quantity' => 30,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            60 =>
            [
                'id' => 95,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-03-24 14:56:09',
                'transaction_modified_date' => '2006-04-04 11:06:13',
                'product_id' => 40,
                'quantity' => 30,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            61 =>
            [
                'id' => 96,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-30 16:46:34',
                'transaction_modified_date' => '2006-03-30 16:46:34',
                'product_id' => 34,
                'quantity' => 12,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            62 =>
            [
                'id' => 97,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-30 17:23:27',
                'transaction_modified_date' => '2006-03-30 17:23:27',
                'product_id' => 34,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            63 =>
            [
                'id' => 98,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-03-30 17:24:33',
                'transaction_modified_date' => '2006-03-30 17:24:33',
                'product_id' => 34,
                'quantity' => 1,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            64 =>
            [
                'id' => 99,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-03 13:50:08',
                'transaction_modified_date' => '2006-04-03 13:50:15',
                'product_id' => 48,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            65 =>
            [
                'id' => 100,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:00:54',
                'transaction_modified_date' => '2006-04-04 11:00:54',
                'product_id' => 57,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            66 =>
            [
                'id' => 101,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:00:56',
                'transaction_modified_date' => '2006-04-04 11:08:49',
                'product_id' => 57,
                'quantity' => 100,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #46',
            ],
            67 =>
            [
                'id' => 102,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:01:14',
                'transaction_modified_date' => '2006-04-04 11:01:14',
                'product_id' => 34,
                'quantity' => 50,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            68 =>
            [
                'id' => 103,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:01:35',
                'transaction_modified_date' => '2006-04-04 11:01:35',
                'product_id' => 43,
                'quantity' => 250,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            69 =>
            [
                'id' => 104,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-04-04 11:01:37',
                'transaction_modified_date' => '2006-04-04 11:01:37',
                'product_id' => 43,
                'quantity' => 300,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #41',
            ],
            70 =>
            [
                'id' => 105,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:01:55',
                'transaction_modified_date' => '2006-04-04 11:01:55',
                'product_id' => 8,
                'quantity' => 25,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            71 =>
            [
                'id' => 106,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:01:58',
                'transaction_modified_date' => '2006-04-04 11:07:37',
                'product_id' => 8,
                'quantity' => 25,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #48',
            ],
            72 =>
            [
                'id' => 107,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:02:17',
                'transaction_modified_date' => '2006-04-04 11:02:17',
                'product_id' => 34,
                'quantity' => 300,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            73 =>
            [
                'id' => 108,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:02:19',
                'transaction_modified_date' => '2006-04-04 11:08:14',
                'product_id' => 34,
                'quantity' => 300,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #47',
            ],
            74 =>
            [
                'id' => 109,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:02:37',
                'transaction_modified_date' => '2006-04-04 11:02:37',
                'product_id' => 19,
                'quantity' => 25,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            75 =>
            [
                'id' => 110,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:02:39',
                'transaction_modified_date' => '2006-04-04 11:41:14',
                'product_id' => 19,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #42',
            ],
            76 =>
            [
                'id' => 111,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:02:56',
                'transaction_modified_date' => '2006-04-04 11:02:56',
                'product_id' => 19,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            77 =>
            [
                'id' => 112,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:02:58',
                'transaction_modified_date' => '2006-04-04 11:07:37',
                'product_id' => 19,
                'quantity' => 25,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #48',
            ],
            78 =>
            [
                'id' => 113,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:03:12',
                'transaction_modified_date' => '2006-04-04 11:03:12',
                'product_id' => 72,
                'quantity' => 50,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            79 =>
            [
                'id' => 114,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:03:14',
                'transaction_modified_date' => '2006-04-04 11:08:49',
                'product_id' => 72,
                'quantity' => 50,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #46',
            ],
            80 =>
            [
                'id' => 115,
                'transaction_type' => 1,
                'transaction_created_date' => '2006-04-04 11:03:38',
                'transaction_modified_date' => '2006-04-04 11:03:38',
                'product_id' => 41,
                'quantity' => 50,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            81 =>
            [
                'id' => 116,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:03:39',
                'transaction_modified_date' => '2006-04-04 11:09:24',
                'product_id' => 41,
                'quantity' => 50,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => 'Fill Back Ordered product, Order #45',
            ],
            82 =>
            [
                'id' => 117,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:04:55',
                'transaction_modified_date' => '2006-04-04 11:05:04',
                'product_id' => 34,
                'quantity' => 87,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            83 =>
            [
                'id' => 118,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:35:50',
                'transaction_modified_date' => '2006-04-04 11:35:54',
                'product_id' => 51,
                'quantity' => 30,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            84 =>
            [
                'id' => 119,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:35:51',
                'transaction_modified_date' => '2006-04-04 11:35:54',
                'product_id' => 7,
                'quantity' => 30,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            85 =>
            [
                'id' => 120,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:36:15',
                'transaction_modified_date' => '2006-04-04 11:36:21',
                'product_id' => 17,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            86 =>
            [
                'id' => 121,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:36:39',
                'transaction_modified_date' => '2006-04-04 11:36:47',
                'product_id' => 6,
                'quantity' => 90,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            87 =>
            [
                'id' => 122,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:37:06',
                'transaction_modified_date' => '2006-04-04 11:37:09',
                'product_id' => 4,
                'quantity' => 30,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            88 =>
            [
                'id' => 123,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:37:45',
                'transaction_modified_date' => '2006-04-04 11:37:49',
                'product_id' => 48,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            89 =>
            [
                'id' => 124,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:38:07',
                'transaction_modified_date' => '2006-04-04 11:38:11',
                'product_id' => 48,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            90 =>
            [
                'id' => 125,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:38:27',
                'transaction_modified_date' => '2006-04-04 11:38:32',
                'product_id' => 41,
                'quantity' => 10,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            91 =>
            [
                'id' => 126,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:38:48',
                'transaction_modified_date' => '2006-04-04 11:38:53',
                'product_id' => 43,
                'quantity' => 5,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            92 =>
            [
                'id' => 127,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:39:12',
                'transaction_modified_date' => '2006-04-04 11:39:29',
                'product_id' => 40,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            93 =>
            [
                'id' => 128,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:39:50',
                'transaction_modified_date' => '2006-04-04 11:39:53',
                'product_id' => 8,
                'quantity' => 20,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            94 =>
            [
                'id' => 129,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:40:13',
                'transaction_modified_date' => '2006-04-04 11:40:16',
                'product_id' => 80,
                'quantity' => 15,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            95 =>
            [
                'id' => 130,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:40:32',
                'transaction_modified_date' => '2006-04-04 11:40:38',
                'product_id' => 74,
                'quantity' => 20,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            96 =>
            [
                'id' => 131,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:41:39',
                'transaction_modified_date' => '2006-04-04 11:41:45',
                'product_id' => 72,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            97 =>
            [
                'id' => 132,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:42:17',
                'transaction_modified_date' => '2006-04-04 11:42:26',
                'product_id' => 3,
                'quantity' => 50,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            98 =>
            [
                'id' => 133,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:42:24',
                'transaction_modified_date' => '2006-04-04 11:42:26',
                'product_id' => 8,
                'quantity' => 3,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            99 =>
            [
                'id' => 134,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:42:48',
                'transaction_modified_date' => '2006-04-04 11:43:08',
                'product_id' => 20,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            100 =>
            [
                'id' => 135,
                'transaction_type' => 2,
                'transaction_created_date' => '2006-04-04 11:43:05',
                'transaction_modified_date' => '2006-04-04 11:43:08',
                'product_id' => 52,
                'quantity' => 40,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            101 =>
            [
                'id' => 136,
                'transaction_type' => 3,
                'transaction_created_date' => '2006-04-25 17:04:05',
                'transaction_modified_date' => '2006-04-25 17:04:57',
                'product_id' => 56,
                'quantity' => 110,
                'purchase_order_id' => null,
                'customer_order_id' => null,
                'comments' => null,
            ],
            ]
        );
    }
}
