<?php

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(
            [
            0 =>
            [
                'id' => 30,
                'employee_id' => 9,
                'customer_id' => 27,
                'order_date' => '2006-01-15 00:00:00',
                'shipped_date' => '2006-01-22 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Karen Toh',
                'ship_address' => '789 27th Street',
                'ship_city' => 'Las Vegas',
                'ship_state_province' => 'NV',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '200.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-01-15 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            1 =>
            [
                'id' => 31,
                'employee_id' => 3,
                'customer_id' => 4,
                'order_date' => '2006-01-20 00:00:00',
                'shipped_date' => '2006-01-22 00:00:00',
                'shipper_id' => 1,
                'ship_name' => 'Christina Lee',
                'ship_address' => '123 4th Street',
                'ship_city' => 'New York',
                'ship_state_province' => 'NY',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '5.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-01-20 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            2 =>
            [
                'id' => 32,
                'employee_id' => 4,
                'customer_id' => 12,
                'order_date' => '2006-01-22 00:00:00',
                'shipped_date' => '2006-01-22 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'John Edwards',
                'ship_address' => '123 12th Street',
                'ship_city' => 'Las Vegas',
                'ship_state_province' => 'NV',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '5.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-01-22 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            3 =>
            [
                'id' => 33,
                'employee_id' => 6,
                'customer_id' => 8,
                'order_date' => '2006-01-30 00:00:00',
                'shipped_date' => '2006-01-31 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Elizabeth Andersen',
                'ship_address' => '123 8th Street',
                'ship_city' => 'Portland',
                'ship_state_province' => 'OR',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '50.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-01-30 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            4 =>
            [
                'id' => 34,
                'employee_id' => 9,
                'customer_id' => 4,
                'order_date' => '2006-02-06 00:00:00',
                'shipped_date' => '2006-02-07 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Christina Lee',
                'ship_address' => '123 4th Street',
                'ship_city' => 'New York',
                'ship_state_province' => 'NY',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '4.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-02-06 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            5 =>
            [
                'id' => 35,
                'employee_id' => 3,
                'customer_id' => 29,
                'order_date' => '2006-02-10 00:00:00',
                'shipped_date' => '2006-02-12 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Soo Jung Lee',
                'ship_address' => '789 29th Street',
                'ship_city' => 'Denver',
                'ship_state_province' => 'CO',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '7.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-02-10 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            6 =>
            [
                'id' => 36,
                'employee_id' => 4,
                'customer_id' => 3,
                'order_date' => '2006-02-23 00:00:00',
                'shipped_date' => '2006-02-25 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Thomas Axen',
                'ship_address' => '123 3rd Street',
                'ship_city' => 'Los Angelas',
                'ship_state_province' => 'CA',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '7.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Cash',
                'paid_date' => '2006-02-23 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            7 =>
            [
                'id' => 37,
                'employee_id' => 8,
                'customer_id' => 6,
                'order_date' => '2006-03-06 00:00:00',
                'shipped_date' => '2006-03-09 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Francisco Pérez-Olaeta',
                'ship_address' => '123 6th Street',
                'ship_city' => 'Milwaukee',
                'ship_state_province' => 'WI',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '12.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-03-06 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            8 =>
            [
                'id' => 38,
                'employee_id' => 9,
                'customer_id' => 28,
                'order_date' => '2006-03-10 00:00:00',
                'shipped_date' => '2006-03-11 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Amritansh Raghav',
                'ship_address' => '789 28th Street',
                'ship_city' => 'Memphis',
                'ship_state_province' => 'TN',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '10.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-03-10 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            9 =>
            [
                'id' => 39,
                'employee_id' => 3,
                'customer_id' => 8,
                'order_date' => '2006-03-22 00:00:00',
                'shipped_date' => '2006-03-24 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Elizabeth Andersen',
                'ship_address' => '123 8th Street',
                'ship_city' => 'Portland',
                'ship_state_province' => 'OR',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '5.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-03-22 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            10 =>
            [
                'id' => 40,
                'employee_id' => 4,
                'customer_id' => 10,
                'order_date' => '2006-03-24 00:00:00',
                'shipped_date' => '2006-03-24 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Roland Wacker',
                'ship_address' => '123 10th Street',
                'ship_city' => 'Chicago',
                'ship_state_province' => 'IL',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '9.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-03-24 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            11 =>
            [
                'id' => 41,
                'employee_id' => 1,
                'customer_id' => 7,
                'order_date' => '2006-03-24 00:00:00',
                'shipped_date' => null,
                'shipper_id' => null,
                'ship_name' => 'Ming-Yang Xie',
                'ship_address' => '123 7th Street',
                'ship_city' => 'Boise',
                'ship_state_province' => 'ID',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => null,
                'paid_date' => null,
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            12 =>
            [
                'id' => 42,
                'employee_id' => 1,
                'customer_id' => 10,
                'order_date' => '2006-03-24 00:00:00',
                'shipped_date' => '2006-04-07 00:00:00',
                'shipper_id' => 1,
                'ship_name' => 'Roland Wacker',
                'ship_address' => '123 10th Street',
                'ship_city' => 'Chicago',
                'ship_state_province' => 'IL',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => null,
                'paid_date' => null,
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 2,
            ],
            13 =>
            [
                'id' => 43,
                'employee_id' => 1,
                'customer_id' => 11,
                'order_date' => '2006-03-24 00:00:00',
                'shipped_date' => null,
                'shipper_id' => 3,
                'ship_name' => 'Peter Krschne',
                'ship_address' => '123 11th Street',
                'ship_city' => 'Miami',
                'ship_state_province' => 'FL',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => null,
                'paid_date' => null,
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            14 =>
            [
                'id' => 44,
                'employee_id' => 1,
                'customer_id' => 1,
                'order_date' => '2006-03-24 00:00:00',
                'shipped_date' => null,
                'shipper_id' => null,
                'ship_name' => 'Anna Bedecs',
                'ship_address' => '123 1st Street',
                'ship_city' => 'Seattle',
                'ship_state_province' => 'WA',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => null,
                'paid_date' => null,
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            15 =>
            [
                'id' => 45,
                'employee_id' => 1,
                'customer_id' => 28,
                'order_date' => '2006-04-07 00:00:00',
                'shipped_date' => '2006-04-07 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Amritansh Raghav',
                'ship_address' => '789 28th Street',
                'ship_city' => 'Memphis',
                'ship_state_province' => 'TN',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '40.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-04-07 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            16 =>
            [
                'id' => 46,
                'employee_id' => 7,
                'customer_id' => 9,
                'order_date' => '2006-04-05 00:00:00',
                'shipped_date' => '2006-04-05 00:00:00',
                'shipper_id' => 1,
                'ship_name' => 'Sven Mortensen',
                'ship_address' => '123 9th Street',
                'ship_city' => 'Salt Lake City',
                'ship_state_province' => 'UT',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '100.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-04-05 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            17 =>
            [
                'id' => 47,
                'employee_id' => 6,
                'customer_id' => 6,
                'order_date' => '2006-04-08 00:00:00',
                'shipped_date' => '2006-04-08 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Francisco Pérez-Olaeta',
                'ship_address' => '123 6th Street',
                'ship_city' => 'Milwaukee',
                'ship_state_province' => 'WI',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '300.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-04-08 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            18 =>
            [
                'id' => 48,
                'employee_id' => 4,
                'customer_id' => 8,
                'order_date' => '2006-04-05 00:00:00',
                'shipped_date' => '2006-04-05 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Elizabeth Andersen',
                'ship_address' => '123 8th Street',
                'ship_city' => 'Portland',
                'ship_state_province' => 'OR',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '50.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-04-05 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            19 =>
            [
                'id' => 50,
                'employee_id' => 9,
                'customer_id' => 25,
                'order_date' => '2006-04-05 00:00:00',
                'shipped_date' => '2006-04-05 00:00:00',
                'shipper_id' => 1,
                'ship_name' => 'John Rodman',
                'ship_address' => '789 25th Street',
                'ship_city' => 'Chicago',
                'ship_state_province' => 'IL',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '5.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Cash',
                'paid_date' => '2006-04-05 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            20 =>
            [
                'id' => 51,
                'employee_id' => 9,
                'customer_id' => 26,
                'order_date' => '2006-04-05 00:00:00',
                'shipped_date' => '2006-04-05 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Run Liu',
                'ship_address' => '789 26th Street',
                'ship_city' => 'Miami',
                'ship_state_province' => 'FL',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '60.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-04-05 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            21 =>
            [
                'id' => 55,
                'employee_id' => 1,
                'customer_id' => 29,
                'order_date' => '2006-04-05 00:00:00',
                'shipped_date' => '2006-04-05 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Soo Jung Lee',
                'ship_address' => '789 29th Street',
                'ship_city' => 'Denver',
                'ship_state_province' => 'CO',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '200.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-04-05 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            22 =>
            [
                'id' => 56,
                'employee_id' => 2,
                'customer_id' => 6,
                'order_date' => '2006-04-03 00:00:00',
                'shipped_date' => '2006-04-03 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Francisco Pérez-Olaeta',
                'ship_address' => '123 6th Street',
                'ship_city' => 'Milwaukee',
                'ship_state_province' => 'WI',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-04-03 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            23 =>
            [
                'id' => 57,
                'employee_id' => 9,
                'customer_id' => 27,
                'order_date' => '2006-04-22 00:00:00',
                'shipped_date' => '2006-04-22 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Karen Toh',
                'ship_address' => '789 27th Street',
                'ship_city' => 'Las Vegas',
                'ship_state_province' => 'NV',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '200.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-04-22 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            24 =>
            [
                'id' => 58,
                'employee_id' => 3,
                'customer_id' => 4,
                'order_date' => '2006-04-22 00:00:00',
                'shipped_date' => '2006-04-22 00:00:00',
                'shipper_id' => 1,
                'ship_name' => 'Christina Lee',
                'ship_address' => '123 4th Street',
                'ship_city' => 'New York',
                'ship_state_province' => 'NY',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '5.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-04-22 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            25 =>
            [
                'id' => 59,
                'employee_id' => 4,
                'customer_id' => 12,
                'order_date' => '2006-04-22 00:00:00',
                'shipped_date' => '2006-04-22 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'John Edwards',
                'ship_address' => '123 12th Street',
                'ship_city' => 'Las Vegas',
                'ship_state_province' => 'NV',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '5.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-04-22 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            26 =>
            [
                'id' => 60,
                'employee_id' => 6,
                'customer_id' => 8,
                'order_date' => '2006-04-30 00:00:00',
                'shipped_date' => '2006-04-30 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Elizabeth Andersen',
                'ship_address' => '123 8th Street',
                'ship_city' => 'Portland',
                'ship_state_province' => 'OR',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '50.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-04-30 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            27 =>
            [
                'id' => 61,
                'employee_id' => 9,
                'customer_id' => 4,
                'order_date' => '2006-04-07 00:00:00',
                'shipped_date' => '2006-04-07 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Christina Lee',
                'ship_address' => '123 4th Street',
                'ship_city' => 'New York',
                'ship_state_province' => 'NY',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '4.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-04-07 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            28 =>
            [
                'id' => 62,
                'employee_id' => 3,
                'customer_id' => 29,
                'order_date' => '2006-04-12 00:00:00',
                'shipped_date' => '2006-04-12 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Soo Jung Lee',
                'ship_address' => '789 29th Street',
                'ship_city' => 'Denver',
                'ship_state_province' => 'CO',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '7.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-04-12 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            29 =>
            [
                'id' => 63,
                'employee_id' => 4,
                'customer_id' => 3,
                'order_date' => '2006-04-25 00:00:00',
                'shipped_date' => '2006-04-25 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Thomas Axen',
                'ship_address' => '123 3rd Street',
                'ship_city' => 'Los Angelas',
                'ship_state_province' => 'CA',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '7.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Cash',
                'paid_date' => '2006-04-25 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            30 =>
            [
                'id' => 64,
                'employee_id' => 8,
                'customer_id' => 6,
                'order_date' => '2006-05-09 00:00:00',
                'shipped_date' => '2006-05-09 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Francisco Pérez-Olaeta',
                'ship_address' => '123 6th Street',
                'ship_city' => 'Milwaukee',
                'ship_state_province' => 'WI',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '12.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-05-09 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            31 =>
            [
                'id' => 65,
                'employee_id' => 9,
                'customer_id' => 28,
                'order_date' => '2006-05-11 00:00:00',
                'shipped_date' => '2006-05-11 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Amritansh Raghav',
                'ship_address' => '789 28th Street',
                'ship_city' => 'Memphis',
                'ship_state_province' => 'TN',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '10.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-05-11 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            32 =>
            [
                'id' => 66,
                'employee_id' => 3,
                'customer_id' => 8,
                'order_date' => '2006-05-24 00:00:00',
                'shipped_date' => '2006-05-24 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Elizabeth Andersen',
                'ship_address' => '123 8th Street',
                'ship_city' => 'Portland',
                'ship_state_province' => 'OR',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '5.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-05-24 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            33 =>
            [
                'id' => 67,
                'employee_id' => 4,
                'customer_id' => 10,
                'order_date' => '2006-05-24 00:00:00',
                'shipped_date' => '2006-05-24 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Roland Wacker',
                'ship_address' => '123 10th Street',
                'ship_city' => 'Chicago',
                'ship_state_province' => 'IL',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '9.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-05-24 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            34 =>
            [
                'id' => 68,
                'employee_id' => 1,
                'customer_id' => 7,
                'order_date' => '2006-05-24 00:00:00',
                'shipped_date' => null,
                'shipper_id' => null,
                'ship_name' => 'Ming-Yang Xie',
                'ship_address' => '123 7th Street',
                'ship_city' => 'Boise',
                'ship_state_province' => 'ID',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => null,
                'paid_date' => null,
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            35 =>
            [
                'id' => 69,
                'employee_id' => 1,
                'customer_id' => 10,
                'order_date' => '2006-05-24 00:00:00',
                'shipped_date' => null,
                'shipper_id' => 1,
                'ship_name' => 'Roland Wacker',
                'ship_address' => '123 10th Street',
                'ship_city' => 'Chicago',
                'ship_state_province' => 'IL',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => null,
                'paid_date' => null,
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            36 =>
            [
                'id' => 70,
                'employee_id' => 1,
                'customer_id' => 11,
                'order_date' => '2006-05-24 00:00:00',
                'shipped_date' => null,
                'shipper_id' => 3,
                'ship_name' => 'Peter Krschne',
                'ship_address' => '123 11th Street',
                'ship_city' => 'Miami',
                'ship_state_province' => 'FL',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => null,
                'paid_date' => null,
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            37 =>
            [
                'id' => 71,
                'employee_id' => 1,
                'customer_id' => 1,
                'order_date' => '2006-05-24 00:00:00',
                'shipped_date' => null,
                'shipper_id' => 3,
                'ship_name' => 'Anna Bedecs',
                'ship_address' => '123 1st Street',
                'ship_city' => 'Seattle',
                'ship_state_province' => 'WA',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => null,
                'paid_date' => null,
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            38 =>
            [
                'id' => 72,
                'employee_id' => 1,
                'customer_id' => 28,
                'order_date' => '2006-06-07 00:00:00',
                'shipped_date' => '2006-06-07 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Amritansh Raghav',
                'ship_address' => '789 28th Street',
                'ship_city' => 'Memphis',
                'ship_state_province' => 'TN',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '40.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-06-07 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            39 =>
            [
                'id' => 73,
                'employee_id' => 7,
                'customer_id' => 9,
                'order_date' => '2006-06-05 00:00:00',
                'shipped_date' => '2006-06-05 00:00:00',
                'shipper_id' => 1,
                'ship_name' => 'Sven Mortensen',
                'ship_address' => '123 9th Street',
                'ship_city' => 'Salt Lake City',
                'ship_state_province' => 'UT',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '100.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-06-05 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            40 =>
            [
                'id' => 74,
                'employee_id' => 6,
                'customer_id' => 6,
                'order_date' => '2006-06-08 00:00:00',
                'shipped_date' => '2006-06-08 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Francisco Pérez-Olaeta',
                'ship_address' => '123 6th Street',
                'ship_city' => 'Milwaukee',
                'ship_state_province' => 'WI',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '300.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-06-08 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            41 =>
            [
                'id' => 75,
                'employee_id' => 4,
                'customer_id' => 8,
                'order_date' => '2006-06-05 00:00:00',
                'shipped_date' => '2006-06-05 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Elizabeth Andersen',
                'ship_address' => '123 8th Street',
                'ship_city' => 'Portland',
                'ship_state_province' => 'OR',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '50.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-06-05 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            42 =>
            [
                'id' => 76,
                'employee_id' => 9,
                'customer_id' => 25,
                'order_date' => '2006-06-05 00:00:00',
                'shipped_date' => '2006-06-05 00:00:00',
                'shipper_id' => 1,
                'ship_name' => 'John Rodman',
                'ship_address' => '789 25th Street',
                'ship_city' => 'Chicago',
                'ship_state_province' => 'IL',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '5.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Cash',
                'paid_date' => '2006-06-05 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            43 =>
            [
                'id' => 77,
                'employee_id' => 9,
                'customer_id' => 26,
                'order_date' => '2006-06-05 00:00:00',
                'shipped_date' => '2006-06-05 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Run Liu',
                'ship_address' => '789 26th Street',
                'ship_city' => 'Miami',
                'ship_state_province' => 'FL',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '60.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Credit Card',
                'paid_date' => '2006-06-05 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            44 =>
            [
                'id' => 78,
                'employee_id' => 1,
                'customer_id' => 29,
                'order_date' => '2006-06-05 00:00:00',
                'shipped_date' => '2006-06-05 00:00:00',
                'shipper_id' => 2,
                'ship_name' => 'Soo Jung Lee',
                'ship_address' => '789 29th Street',
                'ship_city' => 'Denver',
                'ship_state_province' => 'CO',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '200.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-06-05 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            45 =>
            [
                'id' => 79,
                'employee_id' => 2,
                'customer_id' => 6,
                'order_date' => '2006-06-23 00:00:00',
                'shipped_date' => '2006-06-23 00:00:00',
                'shipper_id' => 3,
                'ship_name' => 'Francisco Pérez-Olaeta',
                'ship_address' => '123 6th Street',
                'ship_city' => 'Milwaukee',
                'ship_state_province' => 'WI',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => 'Check',
                'paid_date' => '2006-06-23 00:00:00',
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 3,
            ],
            46 =>
            [
                'id' => 80,
                'employee_id' => 2,
                'customer_id' => 4,
                'order_date' => '2006-04-25 17:03:55',
                'shipped_date' => null,
                'shipper_id' => null,
                'ship_name' => 'Christina Lee',
                'ship_address' => '123 4th Street',
                'ship_city' => 'New York',
                'ship_state_province' => 'NY',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => null,
                'paid_date' => null,
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            47 =>
            [
                'id' => 81,
                'employee_id' => 2,
                'customer_id' => 3,
                'order_date' => '2006-04-25 17:26:53',
                'shipped_date' => null,
                'shipper_id' => null,
                'ship_name' => 'Thomas Axen',
                'ship_address' => '123 3rd Street',
                'ship_city' => 'Los Angelas',
                'ship_state_province' => 'CA',
                'ship_zip_postal_code' => '99999',
                'ship_country_region' => 'USA',
                'shipping_fee' => '0.0000',
                'taxes' => '0.0000',
                'payment_type' => null,
                'paid_date' => null,
                'notes' => null,
                'tax_rate' => 0,
                'tax_status_id' => null,
                'status_id' => 0,
            ],
            ]
        );
    }
}
